[package]
name = "xecs"
version = "0.1.0"
authors = ["xstater@a166224@gmail.com"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xsparseset = { versoin = "0.1.2", git = "https://github.com/xstater/xsparseset" }
